version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unstable
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data